/* eslint-disable operator-linebreak */

// WEB3 CONTEXT
export const SET_WEB3_PROVIDER = "SET_WEB3_PROVIDER";
export const SET_ADDRESS = "SET_ADDRESS";
export const RESET_WEB3_PROVIDER = "RESET_WEB3_PROVIDER";

// CAMPAIGN FORM
export const SET_CAMPAIGN_FORM_ORGRANIZATION =
  "SET_CAMPAIGN_FORM_ORGRANIZATION";
export const SET_CAMPAIGN_FORM_EMAIL = "SET_CAMPAIGN_FORM_EMAIL";
export const SET_CAMPAIGN_FORM_TITLE = "SET_CAMPAIGN_FORM_TITLE";
export const SET_CAMPAIGN_FORM_DESCRIPTION = "SET_CAMPAIGN_FORM_DESCRIPTION";
export const SET_CAMPAIGN_FORM_AMOUNT = "SET_CAMPAIGN_FORM_AMOUNT";
export const SET_CAMPAIGN_FORM_BADGE1 = "SET_CAMPAIGN_FORM_BADGE1";
export const SET_CAMPAIGN_FORM_BADGE2 = "SET_CAMPAIGN_FORM_BADGE2";
export const SET_CAMPAIGN_FORM_BADGE3 = "SET_CAMPAIGN_FORM_BADGE3";
export const SET_CAMPAIGN_FORM_TNC = "SET_CAMPAIGN_FORM_TNC";
export const SET_CAMPAIGN_FORM_RESET = "SET_CAMPAIGN_FORM_RESET";
